name: Deploy Frontend to Hostinger

on:
  push:
    branches: [main]
    paths:
      - 'apps/frontend/**'
      - 'packages/ui/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd apps/frontend
          npm ci

      - name: Build frontend
        run: |
          cd apps/frontend
          npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
          SOURCE: "apps/frontend/.next/"
          REMOTE_HOST: ${{ secrets.HOSTINGER_HOST }}
          REMOTE_USER: ${{ secrets.HOSTINGER_USER }}
          TARGET: ${{ secrets.HOSTINGER_FRONTEND_PATH }}
          EXCLUDE: "/dist/, /node_modules/"

      - name: Notify deployment
        run: |
          echo "Frontend deployed successfully to Hostinger!"
          echo "Deployment time: $(date)"
